In [4]:
import numpy as np #mengolah data berbentuk matriks dan vektor
import pandas as pd #pengolahan data lebih berstruktur (dataset yang punya tabuler)


from sklearn.preprocessing import LabelEncoder #konversi data dari str jadi tabel numerik
from sklearn.model_selection import train_test_split #pembagian data/split data kedalam data train dan juga data tetsting
from sklearn.preprocessing import StandardScaler #mengskala data numerik agar antar data memiliki rentang data yg tidak terlalu jauh
from sklearn.naive_bayes import GaussianNB #melakukan klasifikasi
from sklearn.metrics import confusion_matrix # untuk menguji kenerja model
from sklearn.metrics import classification_report # metode evaluasi klasifikasi
from sklearn.metrics import accuracy_score #sama 

In [7]:
dataset = pd.read_excel('fruit.xlsx')
dataset.head()

diameter  weight  red  green  blue    name
0      2.96   86.76  172     85     2  orange
1      3.91   88.05  166     78     3  orange
2      4.42   95.17  156     81     2  orange
3      4.47   95.60  163     81     4  orange
4      4.48   95.76  161     72     9  orange

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   diameter  10000 non-null  float64
 1   weight    10000 non-null  float64
 2   red       10000 non-null  int64  
 3   green     10000 non-null  int64  
 4   blue      10000 non-null  int64  
 5   name      10000 non-null  object 
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [10]:
dataset.empty

False

In [11]:
en = LabelEncoder()

dataset['name'] = en.fit_transform(dataset['name'])
dataset.head()#melakukan label encoder dataset name

diameter  weight  red  green  blue  name
0      2.96   86.76  172     85     2     1
1      3.91   88.05  166     78     3     1
2      4.42   95.17  156     81     2     1
3      4.47   95.60  163     81     4     1
4      4.48   95.76  161     72     9     1

In [18]:
x = dataset.iloc[:, :-1].values #menunjukan semua data akan digunakan mulai dari baris awal hingga baris akhir, data yg digunakan seluruh col kec kol terakhir
y = dataset.iloc[:, -1].values #isi y 1 kolom terakhir

In [20]:
print(x)

[[  2.96  86.76 172.    85.     2.  ]
 [  3.91  88.05 166.    78.     3.  ]
 [  4.42  95.17 156.    81.     2.  ]
 ...
 [ 15.59 256.5  168.    82.    20.  ]
 [ 15.92 260.14 142.    72.    11.  ]
 [ 16.45 261.51 152.    74.     2.  ]]


In [21]:
print(y)

[1 1 1 ... 0 0 0]


In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2 , random_state=123) #rasio spliting data dimana data test sebanyak 20% dari jumlah dataset keseluruhan sisanya jadi data train. #randomstate bebas karena menjadi hasil dari spliting data konsisten setiap dijalankan 

print('x_train = ', len(x_train))
print('x_test = ', len(x_test))
print('y_train = ', len(y_train))
print('y_test = ', len(y_test))

x_train =  8000
x_test =  2000
y_train =  8000
y_test =  2000


In [23]:
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

#nilai yang ditampilkan sudah dalam bentuk pengsekalaan dimana antar atribut data sudah mempunyai rentang yang dekat 

In [25]:
print(x_train)

[[ 1.40581808  1.4183702  -0.27199554  1.19324519 -1.03227097]
 [ 0.69304398  0.69950687  0.39571226  0.08064231  0.39822925]
 [-1.35297665 -1.34325454  0.77725958 -0.00494252  0.06811382]
 ...
 [-0.31201879 -0.3847701   0.58648592 -0.34728187  0.28819078]
 [-1.15811755 -1.16721335  0.68187275  1.10766035 -0.48207858]
 [-0.41457621 -0.40015234  0.77725958  1.87792388 -1.03227097]]


In [26]:
print(x_test)

[[-0.69399958 -0.70323649 -1.05945457  0.01508522 -1.03797754]
 [-1.61278044 -1.61118728  0.70092411  0.94731768 -0.81456438]
 [ 1.62876103  1.64227434  0.89652175 -0.74765043  0.52591458]
 ...
 [-0.61657422 -0.61881601  1.18991819  2.47278898 -0.7028578 ]
 [ 0.91644778  0.93520982  1.09211938 -2.01887652 -1.03797754]
 [-1.49922326 -1.46508817  1.87450991  0.60832405 -0.03261832]]


In [27]:
print(y_test)

[1 1 0 ... 1 0 1]


In [28]:
classifier = GaussianNB()
classifier.fit(x_train,y_train)#data yang akan dipelajari
#melakukan klasifikasi menggunakan algoritma naive bayes

GaussianNB()

In [29]:
y_pred = classifier.predict(x_test)
print(y_pred)
#melakukan prediksi base model yang telah dibuat

[1 1 0 ... 1 0 1]


In [30]:
classifier.predict_proba(x_test)

array([[3.53858876e-03, 9.96461411e-01],
       [4.25113435e-07, 9.99999575e-01],
       [9.99997968e-01, 2.03169090e-06],
       ...,
       [6.70433428e-05, 9.99932957e-01],
       [9.99564029e-01, 4.35971380e-04],
       [1.80157379e-06, 9.99998198e-01]])

In [31]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
#membandingkan label prediksi dan label sebenarnya
#tahap evaluasi data
#jumlah data terprediksi yang benar dan tidak benar

[[926  80]
 [ 71 923]]


In [32]:
#tahap mendapatkan evaluasi report yang lebih lengkap
akurasi = classification_report(y_test, y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.93      0.92      0.92      1006
           1       0.92      0.93      0.92       994

    accuracy                           0.92      2000
   macro avg       0.92      0.92      0.92      2000
weighted avg       0.92      0.92      0.92      2000



In [33]:
#membaca tingkat akurasi model
akurasi = accuracy_score(y_test, y_pred)
print('tingkat akurasi : %d persen'%(akurasi*100))

tingkat akurasi : 92 persen


In [34]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)
print(ydata)
#untuk membandingkan secara langsung dari hasil y_test dan y_pred

      y_test  y_pred
0          1       1
1          1       1
2          0       0
3          1       1
4          1       1
...      ...     ...
1995       0       0
1996       0       0
1997       1       1
1998       0       0
1999       1       1

[2000 rows x 2 columns]


In [ ]:
ydata.to_excel('dataactualpred.xlsx', index=False)
#untuk medownload data 